# fly.toml file generated for zbroyar on 2023-03-27T21:25:47+03:00

app = "zbroyar"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "waw"
processes = []

[env]
  PORT = "8080"

[deploy]
  release_command = "npx prisma migrate deploy"

[[mounts]]
  source = "images"
  destination = "/app/public/images"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"